//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Terratype.TestSite.Schema
{
	/// <summary>Archetype Map</summary>
	[PublishedContentModel("archetypeMap")]
	public partial class ArchetypeMap : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "archetypeMap";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ArchetypeMap(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ArchetypeMap, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Archetype: This is a desc
		///</summary>
		[ImplementPropertyType("archetype")]
		public Archetype.Models.ArchetypeModel Archetype
		{
			get { return this.GetPropertyValue<Archetype.Models.ArchetypeModel>("archetype"); }
		}

		///<summary>
		/// bing
		///</summary>
		[ImplementPropertyType("bing")]
		public Archetype.Models.ArchetypeModel Bing
		{
			get { return this.GetPropertyValue<Archetype.Models.ArchetypeModel>("bing"); }
		}

		///<summary>
		/// leaflet
		///</summary>
		[ImplementPropertyType("leaflet")]
		public Archetype.Models.ArchetypeModel Leaflet
		{
			get { return this.GetPropertyValue<Archetype.Models.ArchetypeModel>("leaflet"); }
		}
	}
}
