//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Terratype.TestSite.Schema
{
	/// <summary>Mappy</summary>
	[PublishedContentModel("mappy")]
	public partial class Mappy : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "mappy";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Mappy(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Mappy, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// bing
		///</summary>
		[ImplementPropertyType("bing")]
		public Terratype.Models.Model Bing
		{
			get { return this.GetPropertyValue<Terratype.Models.Model>("bing"); }
		}

		///<summary>
		/// c1
		///</summary>
		[ImplementPropertyType("c1")]
		public Terratype.Models.Model C1
		{
			get { return this.GetPropertyValue<Terratype.Models.Model>("c1"); }
		}

		///<summary>
		/// c2
		///</summary>
		[ImplementPropertyType("c2")]
		public Terratype.Models.Model C2
		{
			get { return this.GetPropertyValue<Terratype.Models.Model>("c2"); }
		}

		///<summary>
		/// c3
		///</summary>
		[ImplementPropertyType("c3")]
		public Terratype.Models.Model C3
		{
			get { return this.GetPropertyValue<Terratype.Models.Model>("c3"); }
		}

		///<summary>
		/// l1
		///</summary>
		[ImplementPropertyType("l1")]
		public Terratype.Models.Model L1
		{
			get { return this.GetPropertyValue<Terratype.Models.Model>("l1"); }
		}

		///<summary>
		/// map2: map description
		///</summary>
		[ImplementPropertyType("map2")]
		public Terratype.Models.Model Map2
		{
			get { return this.GetPropertyValue<Terratype.Models.Model>("map2"); }
		}

		///<summary>
		/// map44
		///</summary>
		[ImplementPropertyType("map44")]
		public Terratype.Models.Model Map44
		{
			get { return this.GetPropertyValue<Terratype.Models.Model>("map44"); }
		}

		///<summary>
		/// maps: List of places
		///</summary>
		[ImplementPropertyType("maps")]
		public Archetype.Models.ArchetypeModel Maps
		{
			get { return this.GetPropertyValue<Archetype.Models.ArchetypeModel>("maps"); }
		}

		///<summary>
		/// nesty: Some text to say this is nested content
		///</summary>
		[ImplementPropertyType("nesty")]
		public IEnumerable<IPublishedContent> Nesty
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("nesty"); }
		}

		///<summary>
		/// Text1
		///</summary>
		[ImplementPropertyType("text1")]
		public string Text1
		{
			get { return this.GetPropertyValue<string>("text1"); }
		}

		///<summary>
		/// Text2
		///</summary>
		[ImplementPropertyType("text2")]
		public string Text2
		{
			get { return this.GetPropertyValue<string>("text2"); }
		}
	}
}
